[package]
name = "volute"
version = "1.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

authors = ["Gabriel Gouvine <gabriel.gouvine_cargo@m4x.org>"]
description = "Boolean functions implementation, represented as lookup tables"
license = "MIT OR Apache-2.0"
keywords = ["boolean", "logic", "lut", "lookup-table", "truth-table"]
repository = "https://github.com/Coloquinte/volute"
homepage = "https://github.com/Coloquinte/volute"
categories = ["mathematics", "algorithms"]

[dependencies]
rand = { version = "0.8.5", optional = true }
good_lp = { version = "1.7", features = ["highs"], default-features = false, optional = true }

[features]
default = ["rand"]
rand = ["dep:rand"]
optim-mip = ["dep:good_lp"]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "canonization"
harness = false
